name: null

channels:
  - pytorch
  - conda-forge
  - nodefaults

dependencies:
  - ccache
  - cmake
  - diskcache
  - git-lfs
  - jupyterlab
  - jupyterlab-lsp
  - numpy
  - pip
  - pip:
    - -r requirements-metal-gpu.txt
  - pkg-config
  - protobuf
  - python<=3.12
  - python-lsp-server
  - pytorch
  - sentencepiece
  - tqdm
  - transformers
