name: null

channels:
  - conda-forge
  - nodefaults

dependencies:
  - ccache
  - cmake
  - cxx-compiler
  - diskcache
  - jupyterlab
  - jupyterlab-lsp
  - numpy
  - pip
  - pip:
    - -r requirements.txt
  - python
  - python-lsp-server
  - tqdm
