name: null

channels:
  - conda-forge
  - nodefaults

dependencies:
  - ccache
  - cmake
  - diskcache
  - jupyterlab
  - jupyterlab-lsp
  - numpy
  - pip
  - pip:
    - -r requirements-metal-gpu.txt
  - pkg-config
  - python
  - python-lsp-server
  - tqdm
