name: null

channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  - blas=*=openblas
  - ccache
  - cmake
  - cuda-nvcc
  - cuda-toolkit
  - cxx-compiler
  - diskcache
  - git-lfs
  - huggingface_hub
  - jupyterlab
  - jupyterlab-lsp
  - jupyterlab-nvdashboard
  - numpy
  - pip
  - pip:
    - -r requirements-nvidia-gpu.txt
  - protobuf
  - python
  - python-dotenv
  - python-lsp-server
  - pytorch-cuda=12.4
  - tqdm
  - sentencepiece
  - transformers

